# Generated by Django 5.2.6 on 2025-09-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_match_score', models.FloatField(default=0.0)),
                ('soft_match_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('matched_qualifications', models.JSONField(default=list)),
                ('missing_qualifications', models.JSONField(default=list)),
                ('verdict', models.CharField(choices=[('high', 'High Suitability'), ('medium', 'Medium Suitability'), ('low', 'Low Suitability')], max_length=10)),
                ('feedback', models.TextField(blank=True)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('resume', 'job_description')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('execution_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation')),
            ],
        ),
    ]
