# Generated by Django 5.2.6 on 2026-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='positions_required',
            field=models.PositiveIntegerField(default=1, help_text='Number of students/candidates required'),
        ),
    ]
